=== ArtemKolganow/trainingRep/task13/src/main/resources/xml/xmlTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/xmlTest"
        xmlns:tns="http://www.training.by/xmlTest"
        elementFormDefault="qualified">
    <element name="users">
        <complexType>
            <sequence>
                <element name="user"
                         type="tns:User"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="User">
        <sequence>
            <element name="login" type="string" />
            <element name="pass" type="string" />
            <element name="email" type="string" />
            <element name="userInfo" type="tns:UserInfo" />
            <element name="order" type="tns:Order" minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="int"  use="required" />
        <attribute name="role" type="int"  use="required" >
            <simpleType>
                <restriction base="int">
                    <enumeration value="0"/>
                    <enumeration value="1"/>
                    <enumeration value="2"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="UserInfo">
        <sequence>
            <element name="name" type="string" />
            <element name="surname" type="string" />
            <element name="phoneNumber" type="string" minOccurs="9"
                     maxOccurs="9" />
        </sequence>
    </complexType>
    <complexType name="Order">
        <sequence>
            <element name="date" type="date" />
            <element name="deliviredate" type="date"/>
            <element name="price" type="string" />
            <element name="productlist" type="tns:ProductList" />
        </sequence>
        <attribute name="id" type="int"  use="required" />
        <attribute name="status" type="string"  use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="compilation"/>
                    <enumeration value="confirmed"/>
                    <enumeration value="assembled"/>
                    <enumeration value="delivered"/>
                </restriction>
            </simpleType>
        </attribute>

    </complexType>
    <complexType name="ProductList">
        <sequence>
            <element name="product" type="tns:Product" minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="Product">
        <sequence>
            <element name="product_id" type="int"/>
            <element name="quantity" type="int"/>
        </sequence>
    </complexType>
</schema>

=== ArtemKolganow/trainingRep/task13/target/classes/xml/xmlTest.xml
<?xml version ="1.0" encoding = "UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.training.by/xmlTest"
          xsi:schemaLocation="http://www.training.by/xmlTest xmlTest.xsd">
    <user id="1" role ="2">
        <login>admin</login>
        <pass>123456</pass>
        <email>admin@gmail.com</email>
        <userInfo>
            <name>Артем</name>
            <surname>Колганов</surname>
            <phoneNumber>291111111</phoneNumber>
        </userInfo>
        <order id="1" status="compilation">
            <date>01.02.2020</date>
            <deliviredate>05.03.2020</deliviredate>
            <price>30.5</price>
            <productlist>
                <product>
                    <product_id>1</product_id>
                    <quantity>3</quantity>
                </product>
                <product>
                    <product_id>2</product_id>
                    <quantity>5</quantity>
                </product>
            </productlist>
        </order>
    </user>

    <user id="2" role ="1">
        <login>ant</login>
        <pass>222333</pass>
        <email>ant_is_good@gmail.com</email>
        <userInfo>
            <name>Василий</name>
            <surname>Муравьев</surname>
            <phoneNumber>292222222</phoneNumber>
        </userInfo>
        <order id="2" status="compilation">
            <date>03.02.2020</date>
            <deliviredate>01.03.2020</deliviredate>
            <price>15.6</price>
            <productlist>
                <product>
                    <product_id>1</product_id>
                    <quantity>1</quantity>
                </product>
                <product>
                    <product_id>3</product_id>
                    <quantity>1</quantity>
                </product>
                <product>
                    <product_id>2</product_id>
                    <quantity>2</quantity>
                </product>
            </productlist>
        </order>
    </user>

    <user id="3" role ="1">
        <login>boom</login>
        <pass>332211</pass>
        <email>poop@gmail.com</email>
        <userInfo>
            <name>Леонид</name>
            <surname>Деминов</surname>
            <phoneNumber>293333333</phoneNumber>
        </userInfo>
        <order id="3" status="confirmed">
            <date>10.01.2020</date>
            <deliviredate>20.03.2020</deliviredate>
            <price>22.0</price>
            <productlist>
                <product>
                    <product_id>2</product_id>
                    <quantity>10</quantity>
                </product>
            </productlist>
        </order>
    </user>
</users>
